name: Node CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup csc.exe
      uses: yoavain/Setup-CSC@v5

    - name: Dependencies Install
      run: npm install
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Build
      run: npm run build
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Pre-Publish
      run: |
        FOR /F "tokens=*" %g IN ('node -e "console.log(require(""./package.json"").version)"') do (SET VERSION=%g)
        npm i -g create-windowless-app-%VERSION%.tgz
        create-windowless-app pre-commit-test-app
      shell: cmd
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: create-windowless-app-*.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
